"""update rel

Revision ID: 30b23de48128
Revises: da06ba3e3316
Create Date: 2023-09-30 12:16:45.722336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b23de48128'
down_revision = 'da06ba3e3316'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
