"""Add relationships

Revision ID: 8dd7ddbefc8a
Revises: 462a0cdb874e
Create Date: 2023-09-30 11:23:48.580342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd7ddbefc8a'
down_revision = '462a0cdb874e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
