"""Add relationships

Revision ID: da06ba3e3316
Revises: 8dd7ddbefc8a
Create Date: 2023-09-30 11:24:37.131234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da06ba3e3316'
down_revision = '8dd7ddbefc8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
